[package]
name = "smwe_project"
version = "0.1.0"
authors = ["Adanos020 <adanos020@gmail.com>", "Jakub Szewczyk (kubasz)"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smwe_rom = { path = "../smwe_rom" }
