[workspace]

members = [
    "smwe_project",
    "smwe_rom",
]

[package]
name = "smw-editor"
version = "0.1.0"
authors = ["Adam Gąsior (Adanos020)", "Raven Szewczyk (eigenraven)"]
license = "MIT"
edition = "2021"
readme = "README.md"

[dependencies]
smwe_project = { path = "smwe_project" }
smwe_rom = { path = "smwe_rom" }

glium = "0.30"
imgui = "0.8"
imgui-glium-renderer = "0.8"
imgui-winit-support = "0.8"
inline_tweak = "1.0"
itertools = "0.10"
log = "0.4"
log4rs = "1.0"
nfd2 = "0.3"
num_enum = "0.5"
