[workspace]

members = [
    "smwe_project",
    "smwe_rom",
    "smwe_widgets",
]

[package]
name = "smw-editor"
version = "0.1.0"
authors = ["Adam Gąsior (Adanos020)", "Raven Szewczyk (eigenraven)"]
license = "MIT"
edition = "2021"
readme = "README.md"

[dependencies]
smwe_project = { path = "smwe_project" }
smwe_rom = { path = "smwe_rom" }
smwe_widgets = { path = "smwe_widgets" }

anyhow = "1.0"
eframe = { git = "https://github.com/emilk/egui" }
egui_extras = { git = "https://github.com/emilk/egui" }
inline_tweak = "1.0"
itertools = "0.10"
log = "0.4"
log4rs = "1.0"
nfd2 = "0.3"
num = "0.4"
num_enum = "0.5"
thiserror = "1.0"
