"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
defaults:
  run:
    shell: bash

name: Test with ROM

jobs:
  clippy:
    name: Test on stable Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install development libraries
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-dev libglx-dev libgl1-mesa-dev libsdl2-dev libwayland-dev libx11-dev
      - shell: bash
        run: curl "${{ secrets.SMW_ROM_URL }}" -o ${{ github.workspace }}/rom.smc
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - uses: actions-rs/cargo@v1
        env:
          ROM_PATH: ${{ github.workspace }}/rom.smc
        with:
          command: test
          args: -p smwe_rom -- --ignored
